import './globals.css';
import type { Metadata } from 'next';
import { Inter, Open_Sans } from 'next/font/google';
import Footer from '@/components/common/Footer';
import Header from '@/components/common/Header';

const inter = Inter({ subsets: ['latin'] });
const openSans = Open_Sans({ subsets: ['latin'] });
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={`${openSans.className} max-w-screen-2xl flex flex-col items-center w-full mx-auto`}>
                <Header />
                {/* <div className=""></div> */}
                <main className="grow">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
